webtalk_init -webtalk_dir /Orion/GraphHBM/UTIL_IP/IP_4URAM_2W2R/4_uram_wrapper.sim/sim_1/behav/xsim/xsim.dir/uram_2w_2r_x4_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May  8 18:58:45 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "372bfe30-7c4d-4fa6-9026-9e3a4d86f167" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "734553be55f44884838817fb3144665c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900X 12-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4548.059 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "135.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3557051974 -regid "" -xml /Orion/GraphHBM/UTIL_IP/IP_4URAM_2W2R/4_uram_wrapper.sim/sim_1/behav/xsim/xsim.dir/uram_2w_2r_x4_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /Orion/GraphHBM/UTIL_IP/IP_4URAM_2W2R/4_uram_wrapper.sim/sim_1/behav/xsim/xsim.dir/uram_2w_2r_x4_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /Orion/GraphHBM/UTIL_IP/IP_4URAM_2W2R/4_uram_wrapper.sim/sim_1/behav/xsim/xsim.dir/uram_2w_2r_x4_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
