# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uram_wex64/uram_wex64.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64 || ORIG_REF_NAME==uram_wex64} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_0/uram_wex64_uram_2w_2r_we_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_1/uram_wex64_uram_2w_2r_we_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_2/uram_wex64_uram_2w_2r_we_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_0/uram_wex64_uram_2w_2r_we_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_3/uram_wex64_uram_2w_2r_we_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_1/uram_wex64_uram_2w_2r_we_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_0/uram_wex64_uram_2w_2r_we_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_0/uram_wex64_uram_2w_2r_we_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_4/uram_wex64_uram_2w_2r_we_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_2/uram_wex64_uram_2w_2r_we_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_1/uram_wex64_uram_2w_2r_we_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_1/uram_wex64_uram_2w_2r_we_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_0/uram_wex64_uram_2w_2r_we_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_0/uram_wex64_uram_2w_2r_we_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_0/uram_wex64_uram_2w_2r_we_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_0/uram_wex64_uram_2w_2r_we_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_0 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_0} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_5/uram_wex64_uram_2w_2r_we_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_3/uram_wex64_uram_2w_2r_we_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_2/uram_wex64_uram_2w_2r_we_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_2/uram_wex64_uram_2w_2r_we_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_1/uram_wex64_uram_2w_2r_we_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_1/uram_wex64_uram_2w_2r_we_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_1/uram_wex64_uram_2w_2r_we_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_1/uram_wex64_uram_2w_2r_we_7_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_1 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_1} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_6/uram_wex64_uram_2w_2r_we_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_4/uram_wex64_uram_2w_2r_we_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_3/uram_wex64_uram_2w_2r_we_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_3/uram_wex64_uram_2w_2r_we_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_2/uram_wex64_uram_2w_2r_we_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_2/uram_wex64_uram_2w_2r_we_5_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_2/uram_wex64_uram_2w_2r_we_6_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_2/uram_wex64_uram_2w_2r_we_7_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_2 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_2} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_7/uram_wex64_uram_2w_2r_we_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_7 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_7} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_5/uram_wex64_uram_2w_2r_we_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_4/uram_wex64_uram_2w_2r_we_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_4/uram_wex64_uram_2w_2r_we_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_3/uram_wex64_uram_2w_2r_we_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_3/uram_wex64_uram_2w_2r_we_5_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_3/uram_wex64_uram_2w_2r_we_6_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_3/uram_wex64_uram_2w_2r_we_7_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_3 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_3} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_8/uram_wex64_uram_2w_2r_we_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_8 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_8} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_6/uram_wex64_uram_2w_2r_we_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_5/uram_wex64_uram_2w_2r_we_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_5/uram_wex64_uram_2w_2r_we_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_4/uram_wex64_uram_2w_2r_we_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_4/uram_wex64_uram_2w_2r_we_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_4/uram_wex64_uram_2w_2r_we_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_4/uram_wex64_uram_2w_2r_we_7_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_4 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_4} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_9/uram_wex64_uram_2w_2r_we_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_9 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_9} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_7/uram_wex64_uram_2w_2r_we_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_7 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_7} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_6/uram_wex64_uram_2w_2r_we_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_6/uram_wex64_uram_2w_2r_we_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_5/uram_wex64_uram_2w_2r_we_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_5/uram_wex64_uram_2w_2r_we_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_5/uram_wex64_uram_2w_2r_we_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_5/uram_wex64_uram_2w_2r_we_7_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_5 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_5} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_0_10/uram_wex64_uram_2w_2r_we_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_0_10 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_0_10} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_1_8/uram_wex64_uram_2w_2r_we_1_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_1_8 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_1_8} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_2_7/uram_wex64_uram_2w_2r_we_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_2_7 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_2_7} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_3_7/uram_wex64_uram_2w_2r_we_3_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_3_7 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_3_7} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_4_6/uram_wex64_uram_2w_2r_we_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_4_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_4_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_5_6/uram_wex64_uram_2w_2r_we_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_5_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_5_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_6_6/uram_wex64_uram_2w_2r_we_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_6_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_6_6} -quiet] -quiet

# IP: bd/uram_wex64/ip/uram_wex64_uram_2w_2r_we_7_6/uram_wex64_uram_2w_2r_we_7_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex64_uram_2w_2r_we_7_6 || ORIG_REF_NAME==uram_wex64_uram_2w_2r_we_7_6} -quiet] -quiet

# XDC: /Orion/GraphHBM/UTIL_IP/IP_64URAM_2W2R_WE/64_uram_we_wrapper.gen/sources_1/bd/uram_wex64/uram_wex64_ooc.xdc
