# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uram_wex16/uram_wex16.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16 || ORIG_REF_NAME==uram_wex16} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_0_0/uram_wex16_uram_2w_2r_we_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_0_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_0_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_0_1/uram_wex16_uram_2w_2r_we_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_0_1 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_0_1} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_0_2/uram_wex16_uram_2w_2r_we_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_0_2 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_0_2} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_1_0/uram_wex16_uram_2w_2r_we_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_1_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_1_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_0_3/uram_wex16_uram_2w_2r_we_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_0_3 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_0_3} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_1_1/uram_wex16_uram_2w_2r_we_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_1_1 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_1_1} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_4_0/uram_wex16_uram_2w_2r_we_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_4_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_4_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_5_0/uram_wex16_uram_2w_2r_we_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_5_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_5_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_7_0/uram_wex16_uram_2w_2r_we_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_7_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_7_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_8_0/uram_wex16_uram_2w_2r_we_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_8_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_8_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_9_0/uram_wex16_uram_2w_2r_we_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_9_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_9_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_10_0/uram_wex16_uram_2w_2r_we_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_10_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_10_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_11_0/uram_wex16_uram_2w_2r_we_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_11_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_11_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_12_0/uram_wex16_uram_2w_2r_we_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_12_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_12_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_13_0/uram_wex16_uram_2w_2r_we_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_13_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_13_0} -quiet] -quiet

# IP: bd/uram_wex16/ip/uram_wex16_uram_2w_2r_we_14_0/uram_wex16_uram_2w_2r_we_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex16_uram_2w_2r_we_14_0 || ORIG_REF_NAME==uram_wex16_uram_2w_2r_we_14_0} -quiet] -quiet

# XDC: /Orion/GraphHBM/UTIL_IP/IP_16URAM_2W2R_WE/16_uram_we_wrapper.gen/sources_1/bd/uram_wex16/uram_wex16_ooc.xdc
