#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 04 14:50:43 HKT 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto cc7243cdfa1d4eeb9d9f264bdbaeb774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot uram_2w2r_tb_behav xil_defaultlib.uram_2w2r_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto cc7243cdfa1d4eeb9d9f264bdbaeb774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot uram_2w2r_tb_behav xil_defaultlib.uram_2w2r_tb xil_defaultlib.glbl -log elaborate.log

