#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 13 11:19:18 HKT 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim bram_36e2_tb_behav -key {Behavioral:sim_1:Functional:bram_36e2_tb} -tclbatch bram_36e2_tb.tcl -view /Orion/GraphHBM/UTIL_IP/IP_BRAM_32K_2W2R/bram_36e2_tb_behav.wcfg -log simulate.log"
xsim bram_36e2_tb_behav -key {Behavioral:sim_1:Functional:bram_36e2_tb} -tclbatch bram_36e2_tb.tcl -view /Orion/GraphHBM/UTIL_IP/IP_BRAM_32K_2W2R/bram_36e2_tb_behav.wcfg -log simulate.log

