# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uram_wex2/uram_wex2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex2 || ORIG_REF_NAME==uram_wex2} -quiet] -quiet

# IP: bd/uram_wex2/ip/uram_wex2_uram_2w_2r_we_0_0/uram_wex2_uram_2w_2r_we_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex2_uram_2w_2r_we_0_0 || ORIG_REF_NAME==uram_wex2_uram_2w_2r_we_0_0} -quiet] -quiet

# IP: bd/uram_wex2/ip/uram_wex2_uram_2w_2r_we_0_1/uram_wex2_uram_2w_2r_we_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uram_wex2_uram_2w_2r_we_0_1 || ORIG_REF_NAME==uram_wex2_uram_2w_2r_we_0_1} -quiet] -quiet

# XDC: /Orion/GraphHBM/UTIL_IP/IP_2URAM_2W2R_WE/2_uram_we_wrapper.gen/sources_1/bd/uram_wex2/uram_wex2_ooc.xdc
