#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("peID", 8, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("sw_data", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("exist", 1, hls_out, 2, "ap_none", "out_data", 1),
	Port_Property("tmp_dist_0_address0", 12, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("tmp_dist_0_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("tmp_dist_0_we0", 8, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("tmp_dist_0_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("tmp_dist_0_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("tmp_dist_1_address0", 12, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("tmp_dist_1_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("tmp_dist_1_we0", 8, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("tmp_dist_1_d0", 64, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("tmp_dist_1_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("tmp_dist_2_address0", 12, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("tmp_dist_2_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("tmp_dist_2_we0", 8, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("tmp_dist_2_d0", 64, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("tmp_dist_2_q0", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("tmp_dist_3_address0", 12, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("tmp_dist_3_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("tmp_dist_3_we0", 8, hls_out, 6, "ap_memory", "mem_we", 1),
	Port_Property("tmp_dist_3_d0", 64, hls_out, 6, "ap_memory", "mem_din", 1),
	Port_Property("tmp_dist_3_q0", 64, hls_in, 6, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "BFS_Gather";
